require.config({
	baseUrl:"/",
	paths:{
		"jq":"lib/jquery/jquery-1.12.4.min",
		"cookie":"lib/jquery_plugins/jquery.cookie",
		"temp":"lib/arttemplate/template-native",
		"handf":"js/headerfooter"
	}
})
