require.config({
	baseUrl:"/",
	paths:{
		"jquery":"lib/jquery/jquery-1.12.4.min",
		"cookie":"lib/jquery_plugins/jquery.cookie",
		"temp":"lib/arttemplate/template-native",
		"handf":"js/headerfooter",
		"register":"js/register",
		"login":"js/login",
		"nav":"js/nav"
	}
});
